CREATE TABLE TTRPPTPARC
(
	TRPIDT int NOT NULL,
    USRPSD VARCHAR(50) NOT NULL,
    INDUSRPTP VARCHAR(1),
    TRPNOT float8,
    VALDAT date,
    DATEFT timestamp without time zone,
    DATSUP timestamp without time zone NOT NULL,
    CONSTRAINT PK_TTRPPTPARC PRIMARY KEY (TRPIDT, USRPSD, DATEFT)
)
TABLESPACE pg_default;
COMMENT ON TABLE TTRPPTPARC IS 'Trip participant archive table';
COMMENT ON COLUMN TTRPPTPARC.TRPIDT IS 'Trip identifier';
COMMENT ON COLUMN TTRPPTPARC.USRPSD IS 'User pseudo';
COMMENT ON COLUMN TTRPPTPARC.INDUSRPTP IS 'User participated indicator';
COMMENT ON COLUMN TTRPPTPARC.TRPNOT IS 'User note on the trip';
COMMENT ON COLUMN TTRPPTPARC.VALDAT IS 'Validation date';
COMMENT ON COLUMN TTRPPTPARC.DATEFT IS 'Modification date';
COMMENT ON COLUMN TTRPPTPARC.DATSUP IS 'Suppression Date';
