CREATE TABLE TUSRTRPARC
(
	USRIDT int NOT NULL,
    TRPNAM VARCHAR(50) NOT NULL,
    INDUSRPAR VARCHAR(1),
    INDUSRORG VARCHAR(1),
    USRNOT float8,
    TRPMNT float8,
    DATEFT timestamp without time zone,
    DATSUP timestamp without time zone NOT NULL,
    CONSTRAINT PK_TUSRTRPARC PRIMARY KEY (USRIDT, TRPNAM, DATEFT)
)
TABLESPACE pg_default;
    
COMMENT ON TABLE TUSRTRPARC IS 'User trips archive table';
COMMENT ON COLUMN TUSRTRPARC.USRIDT IS 'User identifier';
COMMENT ON COLUMN TUSRTRPARC.INDUSRPAR IS 'User has participated indicator';
COMMENT ON COLUMN TUSRTRPARC.INDUSRORG IS 'User is organizer indicator';
COMMENT ON COLUMN TUSRTRPARC.USRNOT IS 'User note for the trip';
COMMENT ON COLUMN TUSRTRPARC.TRPMNT IS 'Amount spend by user on the trip';
COMMENT ON COLUMN TUSRTRPARC.DATEFT IS 'Modification Date';
COMMENT ON COLUMN TUSRTRPARC.DATSUP IS 'Suppression Date';
