CREATE TABLE TPOTUSR
(
	POTIDT int NOT NULL,
    USRIDT int NOT NULL,
    INDPAY varchar(1),
    CURMNT float8,
    TGTMNT float8,
    INDCANCEL varchar(1),
    CANCELRSN text,
    INDVAL varchar(1),
    CONSTRAINT PK_TPOTUSER PRIMARY KEY (POTIDT, USRIDT)
)
TABLESPACE pg_default;

COMMENT ON TABLE TPOTUSR IS 'Pot participant table';
COMMENT ON COLUMN TPOTUSR.POTIDT IS 'Pot identifier';
COMMENT ON COLUMN TPOTUSR.USRIDT IS 'User identifier';
COMMENT ON COLUMN TPOTUSR.INDPAY IS 'Has payed indicator';
COMMENT ON COLUMN TPOTUSR.CURMNT IS 'Current amount for the user';
COMMENT ON COLUMN TPOTUSR.TGTMNT IS 'Target amount for the user';
COMMENT ON COLUMN TPOTUSR.INDCANCEL IS 'Cancel indicator';
COMMENT ON COLUMN TPOTUSR.CANCELRSN IS 'Cancel Reason';
COMMENT ON COLUMN TPOTUSR.INDVAL IS 'Validation indicator';