CREATE TABLE TUSRTRP
(
	USRIDT int NOT NULL,
    TRPNAM VARCHAR(50) NOT NULL,
    INDUSRPAR VARCHAR(1),
    INDUSRORG VARCHAR(1),
    USRNOT float8,
    TRPMNT float8,
    CONSTRAINT PK_TUSRTRP PRIMARY KEY (USRIDT, TRPNAM)
)
TABLESPACE pg_default;
    
COMMENT ON TABLE TUSRTRP IS 'User trips table';
COMMENT ON COLUMN TUSRTRP.USRIDT IS 'User identifier';
COMMENT ON COLUMN TUSRTRP.INDUSRPAR IS 'User has participated indicator';
COMMENT ON COLUMN TUSRTRP.INDUSRORG IS 'User is organizer indicator';
COMMENT ON COLUMN TUSRTRP.USRNOT IS 'User note for the trip';
COMMENT ON COLUMN TUSRTRP.TRPMNT IS 'Amount spend by user on the trip';
